import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'CMS Debug May Cry',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans antialiased bg-[#0f0f1b] text-[#e0e0e0]`}>
        <div className="flex min-h-screen overflow-hidden">
          <Sidebar />
          <div className="flex-1 flex flex-col min-h-screen">
            <Header />
            <main className="flex-1 bg-[#12151c] p-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
